name: prepare-env

runs:
  using: composite
  steps:
  - name: Setup Go
    uses: actions/setup-go@v5
    with:
      go-version: 1.23.x
  - name: Generate
    shell: bash
    run: |
      go install tool

      go generate ./...
