name: CI
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: "pkg.go.dev publishing"
    runs-on: ubuntu-latest
    steps:
      - name: Publishing new version
        run: |
          curl https://sum.golang.org/lookup/github.com/astavonin/gfsm@${{  github.ref_name }}
